import Vue from 'vue'
import {
  AddressEdit,
  AddressList,
  Area,
  Button,
  Card,
  Cell,
  CellGroup,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  CollapseItem,
  ContactCard,
  ContactEdit,
  ContactList,
  Coupon,
  CouponCell,
  CouponList,
  DatetimePicker,
  Dialog,
  Divider,
  DropdownMenu,
  DropdownItem,
  Empty,
  Field,
  Form,
  Grid,
  GridItem,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Icon,
  Image,
  ImagePreview,
  Info,
  Lazyload,
  List,
  Loading,
  Locale,
  NavBar,
  NoticeBar,
  Notify,
  NumberKeyboard,
  Overlay,
  Pagination,
  Panel,
  PasswordInput,
  Picker,
  Popup,
  Progress,
  PullRefresh,
  Radio,
  RadioGroup,
  Rate,
  Row,
  Search,
  Skeleton,
  Sku,
  Slider,
  Sidebar,
  SidebarItem,
  Step,
  Stepper,
  Steps,
  Sticky,
  SubmitBar,
  Swipe,
  SwipeCell,
  SwipeItem,
  Switch,
  SwitchCell,
  Tab,
  Tabbar,
  TabbarItem,
  Tabs,
  Tag,
  Toast,
  TreeSelect,
  Uploader,
  Cascader,
  CountDown,
  Popover,
} from 'vant'

Vue.use(AddressEdit)
  .use(AddressList)
  .use(Area)
  .use(Button)
  .use(Card)
  .use(Cell)
  .use(CellGroup)
  .use(Checkbox)
  .use(CheckboxGroup)
  .use(Circle)
  .use(Col)
  .use(Collapse)
  .use(CollapseItem)
  .use(ContactCard)
  .use(ContactEdit)
  .use(ContactList)
  .use(Coupon)
  .use(CouponCell)
  .use(CouponList)
  .use(DatetimePicker)
  .use(Dialog)
  .use(Divider)
  .use(DropdownMenu)
  .use(DropdownItem)
  .use(Empty)
  .use(Field)
  .use(Form)
  .use(Grid)
  .use(GridItem)
  .use(GoodsAction)
  .use(GoodsActionIcon)
  .use(GoodsActionButton)
  .use(Icon)
  .use(Image)
  .use(ImagePreview)
  .use(Info)
  .use(Lazyload)
  .use(List)
  .use(Loading)
  .use(Locale)
  .use(NavBar)
  .use(NoticeBar)
  .use(Notify)
  .use(NumberKeyboard)
  .use(Overlay)
  .use(Pagination)
  .use(Panel)
  .use(PasswordInput)
  .use(Picker)
  .use(Popup)
  .use(Progress)
  .use(PullRefresh)
  .use(Radio)
  .use(RadioGroup)
  .use(Rate)
  .use(Row)
  .use(Search)
  .use(Sku)
  .use(Skeleton)
  .use(Slider)
  .use(Sidebar)
  .use(SidebarItem)
  .use(Step)
  .use(Stepper)
  .use(Steps)
  .use(Sticky)
  .use(SubmitBar)
  .use(Swipe)
  .use(SwipeCell)
  .use(SwipeItem)
  .use(Switch)
  .use(SwitchCell)
  .use(Tab)
  .use(Tabbar)
  .use(TabbarItem)
  .use(Tabs)
  .use(Tag)
  .use(Toast)
  .use(TreeSelect)
  .use(Uploader)
  .use(Cascader)
  .use(CountDown)
  .use(Popover)
